### ISSUE TITLE
Argo Plugin SIGSERV

### ISSUE THREAD

**Issue by Baenimyr** [deployKF/deployKF#25]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.1

### Kubernetes Version

```shell
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

### Description

DeployKF plugin is installed as a patch on a default Argo-CD installation.
The DeployKF plugin cannot deploy the "deployKF" app-of-apps because of a null pointer.

### Relevant Logs

```shell
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): plugin sidecar failed. error generating manifests in cmp: rpc error: code = Unknown desc = error generating manifests: `/bin/bash -c "set -eo pipefail\n\n## ensure exactly one of 'source_version' or 'source_path' was provided\nif [[ -n \"$PARAM_SOURCE_VERSION\" && -n \"$PARAM_SOURCE_PATH\" ]]; then\n echo \"ERROR: both 'source_version' and 'source_path' were set, but we require exactly one\" >&2\n exit 1\nelif [[ -z \"$PARAM_SOURCE_VERSION\" && -z \"$PARAM_SOURCE_PATH\" ]]; then\n echo \"ERROR: neither of 'source_version' of 'source_path' were set, but we require exactly one\" >&2\n exit 1\nfi\n\n## ensure exactly one of 'output_kustomize_path' or 'output_helm_path' was provided\nif [[ -n \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" && -n \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n echo \"ERROR: both 'output_kustomize_path' and 'output_helm_path' were set, but we require exactly one\" >&2\n exit 1\nfi\n\n## if no paths are set, default to the argocd app-of-apps\nif [[ -z \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" && -z \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n PARAM_OUTPUT_KUSTOMIZE_PATH=\"./argocd/\"\nfi\n\nDKF_ARGS=()\n\n## set 'deploykf --output-dir' argument\nOUTPUT_DIR=\"./__PLUGIN_GENERATOR_OUTPUT__\"\nDKF_ARGS+=(\"--output-dir\" \"$OUTPUT_DIR\")\n\n## set 'deploykf --source-version' argument\nif [[ -n \"$PARAM_SOURCE_VERSION\" ]]; then\n DKF_ARGS+=(\"--source-version\" \"$PARAM_SOURCE_VERSION\")\nfi\n\n## set 'deploykf --source-path' argument\nif [[ -n \"$PARAM_SOURCE_PATH\" ]]; then\n DKF_ARGS+=(\"--source-path\" \"$PARAM_SOURCE_PATH\")\nfi\n\n## set 'deploykf --values' argument for each 'values_files' path\nfor env_var in ${!PARAM_VALUES_FILES_@}\ndo\n VALUES_FILE_PATH=\"${!env_var}\"\n if [[ ! -f \"$VALUES_FILE_PATH\" ]]; then\n echo \"ERROR: the provided values file '$VALUES_FILE_PATH' does not exist\" >&2\n exit 1\n fi\n DKF_ARGS+=(\"--values\" \"$VALUES_FILE_PATH\")\ndone\n\n## set 'deploykf --values' argument for the provided 'values' string\nif [[ -n \"$PARAM_VALUES\" ]]; then\n USER_VALUES_FILE_PATH=\"./__PLUGIN_USER_VALUES__.yaml\"\n echo \"$PARAM_VALUES\" > \"$USER_VALUES_FILE_PATH\"\n DKF_ARGS+=(\"--values\" \"$USER_VALUES_FILE_PATH\")\nfi\n\n## set 'deploykf --values' argument for values required by the plugin\nREQUIRED_VALUES='{\"argocd\":{\"source\":{\"plugin\":{\"enabled\":true}}}}'\nREQUIRED_VALUES_FILE_PATH=\"./__PLUGIN_REQUIRED_VALUES__.yaml\"\necho \"$REQUIRED_VALUES\" > \"$REQUIRED_VALUES_FILE_PATH\"\nDKF_ARGS+=(\"--values\" \"$REQUIRED_VALUES_FILE_PATH\")\n\n## run the deploykf generator\ndeploykf generate \"${DKF_ARGS[@]}\"\n\n## ensure the provided 'output_kustomize_path' exists\nif [[ -n \"$PARAM_OUTPUT_KUSTOMIZE_PATH\" ]]; then\n OUTPUT_KUSTOMIZE_PATH=$(realpath \"$OUTPUT_DIR/$PARAM_OUTPUT_KUSTOMIZE_PATH\")\n if [[ ! -d \"$OUTPUT_KUSTOMIZE_PATH\" ]]; then\n echo \"ERROR: the provided 'output_kustomize_path' '$OUTPUT_KUSTOMIZE_PATH' does not exist\" >&2\n exit 1\n fi\nfi\n\n## ensure the provided 'output_helm_path' exists\nif [[ -n \"$PARAM_OUTPUT_HELM_PATH\" ]]; then\n OUTPUT_HELM_PATH=$(realpath \"$OUTPUT_DIR/$PARAM_OUTPUT_HELM_PATH\")\n if [[ ! -d \"$OUTPUT_HELM_PATH\" ]]; then\n echo \"ERROR: the provided 'output_helm_path' '$OUTPUT_HELM_PATH' does not exist\" >&2\n exit 1\n fi\n\n ## add the helm repos for the chart dependencies\n helm dependency list --max-col-width 10000 \"$OUTPUT_HELM_PATH\" | awk 'NR>1 {print $1,$3}' | while read -r name url; do\n if [[ -n \"$name\" && -n \"$url\" ]]; then\n helm repo add \"$name\" \"$url\" --insecure-skip-tls-verify\n fi\n done\n\n ## pull the helm chart dependencies\n helm dependency build \"$OUTPUT_HELM_PATH\"\nfi\n"` failed exit status 2: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x189fd30] goroutine 1 [running]: github.com/deployKF/cli/internal/generate.(*SourceHelper).getReleaseByVersion(0xc00052d220, {0x7fff8dad9a44, 0x5}) /home/runner/work/cli/cli/internal/generate/source.go:163 +0xb0 github.com/deployKF/cli/internal/generate.(*SourceHelper).DownloadAndUnpackSource(0xc00052d220, {0x7fff8dad9a44, 0x5}, {0xc000665470, 0x29}, {0x23854a0, 0xc000012018}) /home/runner/work/cli/cli/internal/generate/source.go:70 +0x1d9 github.com/deployKF/cli/cmd/deploykf.(*generateOptions).run(0xc00052d180, {0x23854a0, 0xc000012018}) /home/runner/work/cli/cli/cmd/deploykf/generate.go:123 +0x611 github.com/deployKF/cli/cmd/deploykf.newGenerateCmd.func1(0xc000663800?, {0x1f4df37?, 0xa?, 0xa?}) /home/runner/work/cli/cli/cmd/deploykf/generate.go:76 +0x25 github.com/spf13/cobra.(*Command).execute(0xc000663800, {0xc0004b1720, 0xa, 0xa}) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862 github.com/spf13/cobra.(*Command).ExecuteC(0xc000663500) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd github.com/spf13/cobra.(*Command).Execute(...) /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 github.com/deployKF/cli/cmd/deploykf.Execute() /home/runner/work/cli/cli/cmd/deploykf/root.go:45 +0x2d main.main() /home/runner/work/cli/cli/main.go:6 +0x17
```

### deployKF Values (Optional)

```yaml
default sample-values.yaml and example app-of-apps.yaml
```

**Comment by thesuperzapper** [comment]
@Baenimyr I believe this issue is patched in the plugin version [found in the `main` branch of `deploykf/deploykf`](https://github.com/deployKF/deployKF/tree/main/argocd-plugin), if you are cloning a specific tag, I recommend you install the plugin from `main`.

I probably need to clarify in the readme that the HEAD of `main` is the intended place for people to get the plugin.

Please confirm if this fixes your issue.

**Comment by thesuperzapper** [comment]
@Baenimyr I am going to close this, assuming your issue was fixed by using the latest version of the plugin (which uses the latest version of the deploykf cli, that fixed this problem).

**Comment by Baenimyr** [comment]
The deployKF plugin from the main branch works well now.
But it is not the prefered solution if i need to make some adjustments in the sub-app manifests.

**Comment by thesuperzapper** [comment]
@Baenimyr I would love it if you could raise an issue with some of the things that you are manually changing in the manifest , that way we can create new values to solve the same problem.
